[build]
builder = "nixpacks"
buildCommand = "npm install"

[phases.setup]
nixPkgs = ["nodejs", "python312", "python312Packages.pip"]

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[deploy.env]
NODE_ENV = "production" 